# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02f3ddbd0692531f7468b130733f4ed7568e5e7646a00c9fef85459aaa7537e05c04a4ac342508adf7ed1c041f0f285ef8b7cde9405fae99fb223abc97133fb7

test:
  secret_key_base: 9ab2e1cdfe89781883615c51a85c8dc5cc0d5abd4aad9b475ac05cad6c5b4b2478f44c572173a7365ff184cc4c9aa483bf50fcffb5d10d6015ddf44b8f92e089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
